/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 394e9086e652b1e588e44047ed32878b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		DB: D1Database;
		APP_ORIGIN: "https://app.thelnk.is";
	}
}
interface Env extends Cloudflare.Env {}
