/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc99e09110e3ba3b2da7d674f02b7992)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		DB: D1Database;
		APP_ORIGIN: "https://thelnk.is";
		WEB: Fetcher /* thelnk-web */;
	}
}
interface Env extends Cloudflare.Env {}
