/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5eaea6422a9294bcfb4a4d652b755aa6)
declare namespace Cloudflare {
	interface Env {
		FILES: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		R2_ACCOUNT_ID: "";
		R2_BUCKET_NAME: "thelnk-files";
		PUBLIC_APP_ORIGIN: "https://app.thelnk.is";
		PUBLIC_SHORT_ORIGIN: "https://thelnk.is";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "PUBLIC_APP_ORIGIN" | "PUBLIC_SHORT_ORIGIN">> {}
}
